[project]
name = "xgboost-multiclass"
version = "0.1.0"
description = "An example of redsho optimizing a xgboost multiclass classifier"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "palmerpenguins>=0.1.6",
    "redsho>=0.3.3",
    "scikit-learn>=1.9.1",
    "xgboost-cpu>=3.4.1",
]
